jobs:
  include:
    # ---------------------- LINUX JOBS ----------------------
    - dist: xenial
      os: linux
      deploy:
        - provider: releases
          token: "$GITHUB_APIKEY"
          file: "$FILE_NAME"
          skip_cleanup: true
          dpl_version: 2.0.5
          on:
            tags: true

    - dist: bionic
      os: linux

    # ---------------------- WINDOWS JOBS ----------------------
    - os: windows
      name: "Windows - DPL 1.10.16 ✅"
      deploy:
        - provider: releases
          token: "$GITHUB_APIKEY"
          file: "$FILE_NAME"
          skip_cleanup: true
          dpl_version: 1.10.16
          on:
            tags: true

    - os: windows
      name: "Windows - DPL 2.0.3.beta.4 ✅ (last known good)"
      deploy:
        - provider: releases
          token: "$GITHUB_APIKEY"
          file: "$FILE_NAME"
          skip_cleanup: true
          dpl_version: 2.0.3.beta.4
          on:
            tags: true

    - os: windows
      name: "Windows - DPL 2.0.3.beta.2 ✅"
      deploy:
        - provider: releases
          token: "$GITHUB_APIKEY"
          file: "$FILE_NAME"
          skip_cleanup: true
          dpl_version: 2.0.3.beta.2
          on:
            tags: true

    - os: windows
      name: "Windows - DPL 2.0.3.beta.5 ❌ Skipped"
      script: |
        echo "DPL 2.0.3.beta.5 is not compatible with Ruby 2.7. Skipping..."
        echo "WARNING: Skipping deployment instructions. In this OS environment version, it is not possible to use DPL v2 by default due to compatibility issues between legacy system components and the modern Ruby version. Please use the older DPL v1 instead by modifying only this specific build job recipe to include 'dpl_version: 1.10.16'."
        exit 0

    - os: windows
      name: "Windows - DPL 2.0.4.beta ❌ Skipped"
      script: |
        echo "DPL 2.0.4.beta requires Ruby >= 3.1. Skipping..."
        echo "WARNING: Skipping deployment instructions. In this OS environment version, it is not possible to use DPL v2 by default due to compatibility issues between legacy system components and the modern Ruby version. Please use the older DPL v1 instead by modifying only this specific build job recipe to include 'dpl_version: 1.10.16'."
        exit 0

    - os: windows
      name: "Windows - DPL 2.0.5.1 ❌ Skipped"
      script: |
        echo "DPL 2.0.5.1 requires Ruby >= 3.1. Skipping..."
        echo "WARNING: Skipping deployment instructions. In this OS environment version, it is not possible to use DPL v2 by default due to compatibility issues between legacy system components and the modern Ruby version. Please use the older DPL v1 instead by modifying only this specific build job recipe to include 'dpl_version: 1.10.16'."
        exit 0

    - os: windows
      name: "Windows - DPL 2.0.5.4 ❌ Skipped"
      script: |
        echo "DPL 2.0.5.4 requires Ruby >= 3.1. Skipping..."
        echo "WARNING: Skipping deployment instructions. In this OS environment version, it is not possible to use DPL v2 by default due to compatibility issues between legacy system components and the modern Ruby version. Please use the older DPL v1 instead by modifying only this specific build job recipe to include 'dpl_version: 1.10.16'."
        exit 0
